apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-kube-controller-manager-operator
  name: version-mapping
data:
  "0.0.1-snapshot-kubernetes": "quay.io/openshift/origin-hyperkube:v4.0"
  "0.0.1-snapshot": "docker.io/openshift/origin-cluster-kube-controller-manager-operator:v4.0"
