apiVersion: openshiftcontrolplane.config.openshift.io/v1
kind: OpenShiftControllerManagerConfig
servingInfo:
  bindAddress: 0.0.0.0:10357
  bindNetwork: tcp
  clientCA: /etc/kubernetes/static-pod-certs/configmaps/client-ca/ca-bundle.crt
  certFile: /etc/kubernetes/static-pod-resources/secrets/serving-cert/tls.crt
  keyFile: /etc/kubernetes/static-pod-resources/secrets/serving-cert/tls.key
