apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-controller-manager
  namespace: kube-system
  labels:
    tier: "control-plane"
    k8s-app: "kube-controller-manager"
    openshift.io/control-plane: "true"
    openshift.io/component: "controller"
  annotations:
    openshift.io/run-level: "0"
spec:
  selector:
    matchLabels:
      tier: "control-plane"
      k8s-app: "kube-controller-manager"
      openshift.io/control-plane: "true"
      openshift.io/component: "controller"
  template:
    metadata:
      labels:
        tier: "control-plane"
        k8s-app: "kube-controller-manager"
        openshift.io/control-plane: "true"
        openshift.io/component: "controller"
    spec:
      containers:
      - name: kube-controller-manager
        image: {{ .Image }}
        imagePullPolicy: {{ .ImagePullPolicy }}
        command: ["hypershift", "openshift-kube-controller-manager"]
        args:
        - "--config=/var/run/configmaps/config/config.yaml"
        - "--kubeconfig=/var/run/configmaps/kubeconfig/kubeconfig"
        - "--master=https://kubernetes.default.svc"
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        - mountPath: /var/run/configmaps/kubeconfig
          name: kubeconfig
        - mountPath: /var/run/secrets/service-account-private-key
          name: service-account-private-key
        - mountPath: /var/run/secrets/cluster-signing-ca
          name: cluster-signing-ca
        - mountPath: /var/run/secrets/client-ca
          name: client-ca
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: config
        configMap:
          name: kube-controller-manager-config
      - name: cluster-signing-ca
        secret:
          secretName: cluster-signing-ca
      - name: service-account-private-key
        secret:
          secretName: service-account-private-key
      - name: client-ca
        configMap:
          name: client-ca
      - name: kubeconfig
        secret:
          secretName: controller-manager-kubeconfig
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
